@ST_32991
Feature: Big Description
There are, as you know, just onomatopoeic word, say, "doodle", "croak" or "rustling", "rattles". They indicate and simultaneously draw any sound phenomena. In this word, such as "doodle" is very conditional transfers crowing, it is not an imitation, namely the schematic. Apparently, the sound "to" transmit what is throaty and staccato cry, the sound of the "p" emphasizes his larynx, and the vowels "in-and-e-y" are placed as shown certain painter (the collective artist, the people) is better - from an aesthetic point of view and in terms of relations with other terms of his language (German cock, for example, yelling "kikeriki ', French -' kokariko", and the Chinese in general yells "uouo"). Even onomatopoeic words are not a direct imitation of the phenomenon (the desire, for example, the most approximate to reproduce cock), and conditional image effects, sound pattern, they should be considered from the aesthetic point of view. They are not photographs, but, say, paintings of Cezanne, transmitting not the objects and phenomena, and not even the appearance of them, and their essence, their idea. They have their own structure corresponding to parallel the structure of what they convey. That is, words are not conventional signs (where sound would be arbitrary) and not accurate casts (photos), and the transmitted symbols (works of art).
Sounding objects and phenomena are not so many, most of the objects and phenomena not sound, the voiceless. For example, the "bell" has a voice, and "butterfly" - no. But both of these items are drawn sound. Word does not imitate the phenomenon, and it expresses, gives him "mouth to the revelation."

Paul Florensky in the "magical about the word" notices that the words seem to us only by his miniature short duration, but the tension of time, for example, reception of hashish, are transformed into complex musical works in a complex whole.
Take hashish we will not (any more what wonders a little prividitsya), and listen to what they can tell the children, listening to a word either. I conducted such experiments, for instance, the story of a child about how he sees the word "metro":
M - slowing traffic, the train approaches; E - air flows, dissected train flowing around it; TR - braking and subsequent acceleration, the roar of the receding train; On - the train goes into the tunnel, the air flow remains and echoes.
Where are these comparisons? Why M is perceived as an expression of a child slows down? With a cry of a rooster it was clear about: jerky, guttural cry. And here is where?
Apparently, from three sources simultaneously.
The first source - our body. When we say "m", we mychim, blocking the path of the air. This makes it possible to correlate the sound with deceleration of the word "Metro".
The second source - the ratio of other words language, such as "slow", "slow down." This root is present in the description of the child the word "Metro". The child builds like alliteration, including the word "metro" in some elaborate work of art, in some poem.
Compare the words of Socrates, cited above, "the letter ro corresponds to impulse, movement and at the same time hardness." Here (although the Russian translation, but it's just right handed), Socrates proves his point about the importance of sound "p", for example, the word "rapids" in other words, the language ( "rush" and "hardness"), which also has this sound.
The third source - the inner drawing logic, because the "th" sounds, "e", "t", "p", "about" can mean anything other words, only in the "Metro" words have the meaning which I saw in them a child. In other words, they mean that the above described, namely in a ratio to each other and strictly in this manner. It paints a picture that is written.
If the task of the word was the most accurate, realistic image of the object, the perfect word would be the exact counterpart of the subject, says about Socrates, Cratylus:
"Will there be two different things - Cratylus and Cratylus image if any of the gods reproduce not only the color and contours of your body, as do the artists, but also everything inside - recreate the softness and warmth, motion, your soul and mind - in short, do everything as you have, and deliver this work next to you, whether it's Cratylus Cratylus and the image, or it will be two Cratylus? ... And do not insist on the fact that the name should have only such sounds, which would make it completely identical to the things which it is assigned. "
Then Socrates said that the name is different from their imperfection imenuemogo: "Let's say that some inappropriate letter may then be added." But then the painting could be said that from the fact it is distinguished only imperfection.

Each word in the process of historical development and not just change their sound, and often even their importance. However, the sound image interacts with the changing value driven around like a stone wave, the aesthetic sense of the person.

Imagine the following scene: the primitive man came out of the cave in the morning to get some fresh air (or even for something), and returning, said tribesmen about the weather. The words "cold", for example, yet, it does not exist in its current short form, it is not yet developed, not frozen. And then he starts to blow (depicting the wind): hooo ... Hoo ... rubbing his icy body: LLL ... trembling, showing how he stiffened, zadubela, knocking teeth: ddd ... Could be, of course, with other sounds and gestures . On uttering such words could leave a few minutes. This could be the whole musical picture. This could be a process of creation, creating word-picture, word-poems, the only one of its kind, not intended for re-use, transmitting only this cold here in this situation of communication - that is, the creation of a proper name. And then, apparently, such a great and original primitive word clenched and froze in our little words have become a bargaining chip, a household name.

@SC_172234 @There-are-as-you-know-just-onomatopoeic-word-say-"doodle"-"croak"-or-"rustling"
Scenario Outline: 
Есть, как известно, просто звукоподражательные слова, скажем: «кукареку», «квакать», или: «шелестит», «дребезжит». Они обозначают и одновременно с этим рисуют какие-либо звуковые явления. При этом слово, например, «кукареку» очень условно передает крик петуха, это не подражание, а именно условное изображение. Видимо, звук «к» передает то, что это горловой и отрывистый крик, звук «р» подчеркивает его гортанность, а гласные «у-а-е-у» расставлены так, как показалось некоему художнику (коллективному художнику, народу) лучше — с эстетической точки зрения и в смысле соотношения с другими словами его языка (немецкий петух, например, кричит «кикерики», французский — «кокарико», а китайский вообще кричит «уоуо»). Даже звукоподражательные слова являются не прямым подражанием явлению (стремлением, например, наиболее приближенно воспроизвести петушиный крик), а условным изображением явления, звуковым рисунком, их нужно рассматривать с эстетической точки зрения. Они не фотографии, а, скажем, картины Сезанна, передающие не сами предметы и явления и даже не впечатления от них, а их сущность, их идею. Они обладают своей структурой, соответствующей, параллельной структуре того, что они передают. То есть, слова являются не условными знаками (в которых звучание было бы произвольно) и не точными слепками (фотографиями), а символами передаваемого (художественными произведениями).
Звучащих предметов и явлений не так уж много, большинство предметов и явлений не звучат, безголосы. Например, «колокольчик» имеет голос, а «бабочка» — нет. Но оба эти предмета нарисованы звуком. Слово не подражает явлению, а его выражает, дает ему «рот для откровения».

Павел Флоренский в работе «Магичность слова» замечает, что слова кажутся нам миниатюрными лишь по своей кратковременности, но при растяжении времени, например, приемом гашиша, превращаются в сложные музыкальные произведения, в сложное целое.
Принимать гашиш мы не будем (мало ли еще какие чудеса привидятся), а послушаем то, что могут рассказать дети, вслушиваясь в какое либо слово. Я проводил такие эксперименты, вот, например, рассказ ребенка о том, как он воспринимает слово «метро»:
М — замедляя движение, подходит поезд; Е — потоки воздуха, рассекаемые поездом, обтекающие его; ТР — торможение и последующий разгон, рев удаляющегося поезда; О — поезд уходит в туннель, остается поток воздуха и эхо.
Откуда берутся эти сопоставления? Почему М здесь воспринимается ребенком как выражение замедляющегося движения? С криком петуха было примерно ясно: прерывистый, гортанный крик. А здесь откуда?
Видимо, из трех источников одновременно.
Первый источник — наше тело. Когда мы произносим «м», мы мычим, перегораживая путь воздуху. Это и дает возможность соотнести данный звук с замедлением движения в слове «метро».
Второй источник — соотношение с другими словами языка, например, «медленно», «замедлять». Этот корень присутствует в описании ребенком слова «метро». Ребенок как бы выстраивает аллитерацию, включая слово «метро» в некое более развернутое художественное произведение, в некое стихотворение.
Сравните со словами Сократа, приведенными выше: «буква ро соответствует порыву, движению и в то же время твердости». Здесь (правда в русском переводе, но это как раз верно передано), Сократ подтверждает свою мысль о значении звука «р», например, в слове «стремнина» другими словами языка («порыв» и «твердость»), в которых тоже есть этот звук.
Третий источник — внутренняя логика рисунка, потому что звуки «м», «е», «т», «р», «о» могут означать все что угодно в других словах, и только в слове «метро» имеют то значение, которое увидел в них ребенок. Иными словами, они значат то, что описано выше, именно в соотношении друг с другом и строго в этом порядке. Это краски, которыми написана картинка.
Если бы задачей слова было наиболее точное, реалистическое изображение предмета, то идеальным словом был бы точный двойник предмета, как говорит об этом Сократ Кратилу:
«Будут ли это разные вещи — Кратил и изображение Кратила, если кто-либо из богов воспроизведет не только цвет и очертания твоего тела, как это делают живописцы, но и все, что внутри, — воссоздаст мягкость и теплоту, движения, твою душу и разум — одним словом, сделает все, как у тебя, и поставит это произведение рядом с тобой, будет ли это Кратил и изображение Кратила, или это будут два Кратила? … И не настаивай на том, что имя должно иметь лишь такие звуки, какие делали бы его полностью тождественным вещи, которой оно присвоено».
Затем Сократ говорит, что имя отличается от именуемогo своим несовершенством: «Допусти, что и какая-то неподходящая буква может тут быть добавлена». Но тогда и о картине можно было бы сказать, что от действительности ее отличает лишь несовершенство.
Слово «бабочка» — это не фотография бабочки, это стихотворение о бабочке. Иначе оно звучало бы одинаково на всех языках. На самом же деле каждый народ создает свое стихотворение о бабочке, в котором не только отражает бабочку, но и выражает свое собственное понимание сущности бабочки: «фарфалья» (итальянский), «папийон» (французский), «шметерлинг» (немецкий)... В каждом языке бабочка порхает по-своему, это как бы разные бабочки.
Каждое слово в процессе своего исторического развития не раз меняет и свое звучание, и часто даже свое значение. Однако звуковая картинка взаимодействует с изменяющимся значением, обкатывается, как камень волной, эстетическим чувством человека.

Представим себе следующую картину: первобытный человек вышел утром из пещеры подышать свежим воздухом (или еще для чего-нибудь) и, вернувшись, рассказывает соплеменникам о погоде. Слова «холод», допустим, еще нет, оно не существует в своей нынешней краткой форме, еще не сложилось, не застыло. И вот он начинает дуть (изображая ветер): хооо…хоо…, потирать заледеневшее тело: ллл…, дрожать, показывая, как он одеревенел, задубел, стучать зубами: ддд… Могли бы быть, конечно, при этом и другие звуки и жесты. На произнесение такого слова могло бы уходить несколько минут. Это могло бы быть целой музыкальной картиной. Это могло бы быть процессом творчества, созданием слова-рисунка, слова-стихотворения, единственного в своем роде, не предназначенного для повторных употреблений, передающего только вот этот холод вот в этой ситуации общения, — то есть созданием имени собственного. И только потом, видимо, такие большие и оригинальные первобытные слова сжались и застыли в маленькие наши слова, стали разменной монетой, именами нарицательными.
Given ololo
Then pish-pish <123>

Examples: 
There are, as you know, just onomatopoeic word, say, "doodle", "croak" or "rustling", "rattles". They indicate and simultaneously draw any sound phenomena. In this word, such as "doodle" is very conditional transfers crowing, it is not an imitation, namely the schematic. Apparently, the sound "to" transmit what is throaty and staccato cry, the sound of the "p" emphasizes his larynx, and the vowels "in-and-e-y" are placed as shown certain painter (the collective artist, the people) is better - from an aesthetic point of view and in terms of relations with other terms of his language (German cock, for example, yelling "kikeriki ', French -' kokariko", and the Chinese in general yells "uouo"). Even onomatopoeic words are not a direct imitation of the phenomenon (the desire, for example, the most approximate to reproduce cock), and conditional image effects, sound pattern, they should be considered from the aesthetic point of view. They are not photographs, but, say, paintings of Cezanne, transmitting not the objects and phenomena, and not even the appearance of them, and their essence, their idea. They have their own structure corresponding to parallel the structure of what they convey. That is, words are not conventional signs (where sound would be arbitrary) and not accurate casts (photos), and the transmitted symbols (works of art).
Sounding objects and phenomena are not so many, most of the objects and phenomena not sound, the voiceless. For example, the "bell" has a voice, and "butterfly" - no. But both of these items are drawn sound. Word does not imitate the phenomenon, and it expresses, gives him "mouth to the revelation."

Paul Florensky in the "magical about the word" notices that the words seem to us only by his miniature short duration, but the tension of time, for example, reception of hashish, are transformed into complex musical works in a complex whole.
Take hashish we will not (any more what wonders a little prividitsya), and listen to what they can tell the children, listening to a word either. I conducted such experiments, for instance, the story of a child about how he sees the word "metro":
M - slowing traffic, the train approaches; E - air flows, dissected train flowing around it; TR - braking and subsequent acceleration, the roar of the receding train; On - the train goes into the tunnel, the air flow remains and echoes.
Where are these comparisons? Why M is perceived as an expression of a child slows down? With a cry of a rooster it was clear about: jerky, guttural cry. And here is where?
Apparently, from three sources simultaneously.
The first source - our body. When we say "m", we mychim, blocking the path of the air. This makes it possible to correlate the sound with deceleration of the word "Metro".
The second source - the ratio of other words language, such as "slow", "slow down." This root is present in the description of the child the word "Metro". The child builds like alliteration, including the word "metro" in some elaborate work of art, in some poem.
Compare the words of Socrates, cited above, "the letter ro corresponds to impulse, movement and at the same time hardness." Here (although the Russian translation, but it's just right handed), Socrates proves his point about the importance of sound "p", for example, the word "rapids" in other words, the language ( "rush" and "hardness"), which also has this sound.
The third source - the inner drawing logic, because the "th" sounds, "e", "t", "p", "about" can mean anything other words, only in the "Metro" words have the meaning which I saw in them a child. In other words, they mean that the above described, namely in a ratio to each other and strictly in this manner. It paints a picture that is written.
If the task of the word was the most accurate, realistic image of the object, the perfect word would be the exact counterpart of the subject, says about Socrates, Cratylus:
"Will there be two different things - Cratylus and Cratylus image if any of the gods reproduce not only the color and contours of your body, as do the artists, but also everything inside - recreate the softness and warmth, motion, your soul and mind - in short, do everything as you have, and deliver this work next to you, whether it's Cratylus Cratylus and the image, or it will be two Cratylus? ... And do not insist on the fact that the name should have only such sounds, which would make it completely identical to the things which it is assigned. "
Then Socrates said that the name is different from their imperfection imenuemogo: "Let's say that some inappropriate letter may then be added." But then the painting could be said that from the fact it is distinguished only imperfection.

Each word in the process of historical development and not just change their sound, and often even their importance. However, the sound image interacts with the changing value driven around like a stone wave, the aesthetic sense of the person.

Imagine the following scene: the primitive man came out of the cave in the morning to get some fresh air (or even for something), and returning, said tribesmen about the weather. The words "cold", for example, yet, it does not exist in its current short form, it is not yet developed, not frozen. And then he starts to blow (depicting the wind): hooo ... Hoo ... rubbing his icy body: LLL ... trembling, showing how he stiffened, zadubela, knocking teeth: ddd ... Could be, of course, with other sounds and gestures . On uttering such words could leave a few minutes. This could be the whole musical picture. This could be a process of creation, creating word-picture, word-poems, the only one of its kind, not intended for re-use, transmitting only this cold here in this situation of communication - that is, the creation of a proper name. And then, apparently, such a great and original primitive word clenched and froze in our little words have become a bargaining chip, a household name.
|123|
||